package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/board") // This means URL's start with /board (after Application path)
public class BoardController {
  @Autowired // This means to get the bean called boardRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private BoardRepository boardRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewBoard (@RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Board n = new Board();
    n.setName(name);
    boardRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Board> getAllBoards() {
    // This returns a JSON or XML with the boards
    return boardRepository.findAll();
  }
}