package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/tag") // This means URL's start with /tag (after Application path)
public class TagController {
  @Autowired // This means to get the bean called tagRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TagRepository tagRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewtag (@RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Tag n = new Tag();
    n.setName(name);
    tagRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Tag> getAllTags() {
    // This returns a JSON or XML with the tags
    return tagRepository.findAll();
  }
}